# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [9]:
import numpy as np
x=np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [2]:
import numpy as np
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
import numpy as np
x=np.arange(10,50)
x.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
import numpy as np
x=np.arange(10,50)
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [1]:
import numpy as np
x=np.version
x

<module 'numpy.version' from 'D:\\ANACONDA\\lib\\site-packages\\numpy\\version.py'>

7. Print the dimension of the array in question 3


In [11]:
import numpy as np
x=np.arange(10,50)
x.ndim

1

8. Create a boolean array with all the True values

In [12]:
import numpy as np
x=np.random.randn((10))
x>0

array([ True, False, False,  True, False,  True,  True, False,  True,
       False])

9. Create a two dimensional array




In [9]:
import numpy as np
x=np.arange(0,40)
x.reshape(4,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

10. Create a three dimensional array



In [10]:
import numpy as np
x=np.arange(0,40)
x.reshape(2,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [22]:
import numpy as np
x = np.arange(0,10)
print(x)
x = x[::-1]
print(x)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [21]:
import numpy as np
x=np.zeros((10), dtype=int)
x[5]=1
x

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [17]:
import numpy as np
a=np.array([[1,0,0],[0,1,0],[0,0,1]])
print (a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr2*arr1

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [23]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
x=arr1==arr2
Not_Equal=x.all()
Not_Equal

False

17. Extract all odd numbers from arr with values(0-9)

In [25]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [26]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[a[a % 2 == 1]]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [27]:
import numpy as np
arr = np.arange(10)
np.where(arr>=5,12,arr)

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12])

20. Create a 2d array with 1 on the border and 0 inside

In [30]:
import numpy as np
x = np.ones((4,4))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [34]:
import numpy as np
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [35]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
np.where(arr3d<=3,64,arr3d)

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [38]:
import numpy as np
x=np.arange(0,9)
x.reshape(3,3)
x[0:3:,]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
import numpy as np
x = np.array([[0,1,2], [3,4,5], [6,7,8]])
x[1, 1:2]

array([4])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [14]:
import numpy as np
x = np.array([[0,1,2], [3,4,5], [6,7,8]])
x[0:2,2:3]

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [41]:
import numpy as np
x=np.random.randn(10,10)
np.min(x), np.max(x)

(-3.1894895455460386, 2.135951300121383)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [42]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
x=np.intersect1d(a,b)
x

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [2]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
x=np.extract(names=='Will', data)
x

array([ 1.48434427, -1.95800635])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [3]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
x=np.extract(names=='Will', data)
y=np.extract(names=='Joe', data)
print(x)
print(y)

[-1.81088933 -1.19513277]
[ 2.14218621 -1.17203668 -1.6895237 ]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [16]:
import numpy as np
x=np.arange(1,16 , dtype=float)
x.reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [15]:
import numpy as np
x=np.arange(0,16 , dtype=float)
x.reshape(2,2,4)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

33. Swap axes of the array you created in Question 32

In [17]:
import numpy as np
x=([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])
np.swapaxes(x,1,2)

array([[[ 0.,  4.],
        [ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.]],

       [[ 8., 12.],
        [ 9., 13.],
        [10., 14.],
        [11., 15.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [18]:
import numpy as np
x=np.array([0,1,2,3,4,5,6,7,8,9])
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [19]:
import numpy as np
x=np.random.randn(12)
y=np.random.randn(12)
np.maximum(x,y)

array([-0.96847412, -0.65102641, -0.63867955,  0.63392089,  1.11590886,
        0.08143942, -0.12632559,  0.23681625, -0.11494973,  1.53320817,
        1.12827481, -0.58078708])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [4]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
names.sort()
names

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [1]:
from collections import Counter
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
x = Counter(a)
y = Counter(b)
result_a = sorted((x - y).elements())
result_b = sorted((y - x).elements())
print(result_a)

[1, 2, 3, 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [10]:
import numpy as np

a  = np.array([[34,43,73],[82,22,12],[53,94,66]])

b = np.array([[10,10,10]])

a[1:2] = b[0:1]

print(a)

[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [9]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [1]:
import numpy as np
x=np.random.randn(20)
x.cumsum()
x

array([-0.11269708,  1.12480991,  0.72871647,  0.61886275,  1.43470434,
        1.58190109, -1.16990161,  0.92868494, -0.21650688, -1.27338028,
        0.7115689 , -0.55441823, -1.39838281, -1.51362345, -0.86304232,
       -1.20961423,  0.8308645 ,  1.60585434,  1.11517949,  1.0174456 ])